db_file: "bot.db"

bot_url: "https://t.me/pocketerist_bot"

messages:
  responses:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начала вам необходимо дать мне на это доступ. Для этого перейдите по ссылке:\n%s\nПосле этого можете написать /check для проверки авторизации."
    already_authorized: "Вы уже авторизированы на сервисе."
    auth_success: "Вы успешно авторизированы!"
    saved_success: "Ссылка успешно сохранена."
    unknown_command: "Нераспознанная команда."
  errors:
    default: "Упс, непредвиденная ошибка."
    invalid_url: "Данная ссылка - невалидная."
    unauthorized: "Вы не авторизированы. Используйте команду /start."
    unable_to_save: "Не удалось сохранить ссылку. Попробуйте позже."